services:
  - type: web
    name: modulation-app # ← Change to your app name
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn main:app"
    envVars:
      - key: PORT
        value: 8000
